export const styles = {
  container: {
    maxWidth: "1400px",
    margin: "0 auto",
    padding: "40px 20px",
  },
  header: {
    textAlign: "center",
    marginBottom: "40px",
  },
  h1: {
    fontSize: "48px",
    marginBottom: "10px",
    background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
    backgroundClip: "text",
  },
  subtitle: {
    fontSize: "18px",
    opacity: 0.8,
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(400px, 1fr))",
    gap: "30px",
    marginBottom: "30px",
  },
  card: {
    background: "#000000",
    backdropFilter: "blur(10px)",
    borderRadius: "20px",
    padding: "30px",
    border: "1px solid rgba(255, 255, 255, 0.2)",
  },
  controlGroup: {
    marginBottom: "25px",
  },
  label: {
    display: "block",
    fontWeight: 600,
    marginBottom: "8px",
    fontSize: "14px",
    textTransform: "uppercase",
    letterSpacing: "1px",
    opacity: 0.9,
  },
  input: {
    width: "100%",
    padding: "12px 16px",
    background: "rgba(255, 255, 255, 0.15)",
    border: "2px solid rgba(255, 255, 255, 0.3)",
    borderRadius: "10px",
    color: "white",
    fontSize: "16px",
    transition: "all 0.3s",
  },
  button: {
    width: "100%",
    padding: "16px",
    background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    color: "white",
    border: "none",
    borderRadius: "12px",
    fontSize: "16px",
    fontWeight: 600,
    cursor: "pointer",
    transition: "all 0.3s",
    marginTop: "10px",
  },
  infoBox: {
    background: "rgba(102, 126, 234, 0.2)",
    borderLeft: "4px solid #667eea",
    padding: "15px",
    borderRadius: "8px",
    marginTop: "15px",
    fontSize: "14px",
    lineHeight: 1.6,
  },
  chunkGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(100px, 1fr))",
    gap: "10px",
    marginTop: "15px",
  },
  chunkBox: {
    aspectRatio: "1",
    background: "rgba(255, 255, 255, 0.1)",
    borderRadius: "8px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "12px",
    border: "2px solid transparent",
    transition: "all 0.3s",
    cursor: "pointer",
  },
  stats: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: "15px",
    marginTop: "20px",
  },
  stat: {
    background: "rgba(255, 255, 255, 0.1)",
    padding: "15px",
    borderRadius: "10px",
    textAlign: "center",
  },
  statValue: {
    fontSize: "32px",
    fontWeight: 700,
    display: "block",
    marginBottom: "5px",
  },
  statLabel: {
    fontSize: "12px",
    opacity: 0.8,
    textTransform: "uppercase",
    letterSpacing: "1px",
  },
  checkboxLabel: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "10px",
    marginTop: "20px",
    marginBottom: "10px",
    cursor: "pointer",
    fontSize: "14px",
    userSelect: "none",
  },
  checkbox: {
    width: "18px",
    height: "18px",
    cursor: "pointer",
    accentColor: "#667eea",
  },
  playerWrapper: {
    gridColumn: "1 / -1",
    background: "#000000",
    borderRadius: "20px",
    padding: "20px",
    border: "1px solid rgba(255, 255, 255, 0.1)",
    display: "flex",
    justifyContent: "center",
  },
  codeBlock: {
    background: "rgba(0, 0, 0, 0.5)",
    borderRadius: "12px",
    padding: "20px",
    fontFamily: "'Courier New', monospace",
    fontSize: "13px",
    lineHeight: 1.8,
    overflowX: "auto",
    marginTop: "20px",
    border: "1px solid rgba(255, 255, 255, 0.1)",
    whiteSpace: "pre-wrap",
  }
};

